"""empty message

Revision ID: 100a77119629
Revises: e130fdf37fe7
Create Date: 2024-04-23 12:51:10.323552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '100a77119629'
down_revision = 'e130fdf37fe7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_classroom_association',
    sa.Column('id', sa.Integer(), nullable=False, autoincrement=True),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('classroom_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['classroom.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    )
    with op.batch_alter_table('assessment_score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assessment_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('student_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('classroom_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'assessment_standard', ['assessment_id'], ['id'])
        batch_op.create_foreign_key(None, 'student', ['student_id'], ['id'])
        batch_op.create_foreign_key(None, 'classroom', ['classroom_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment_score', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('student_class_id')
        batch_op.drop_column('assessment_id')

    op.drop_table('student_classroom_association')
    # ### end Alembic commands ###
