"""empty message

Revision ID: 392beac1fb1e
Revises: ae124f47127f
Create Date: 2024-05-14 14:09:48.017466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '392beac1fb1e'
down_revision = 'ae124f47127f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment_standard', schema=None) as batch_op:
        batch_op.alter_column('component_id',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('grade_level',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('period',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(None, 'assessment_component', ['component_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment_standard', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('period',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('grade_level',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('component_id',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)

    # ### end Alembic commands ###
