"""empty message

Revision ID: 3d25b39d2113
Revises: 3c043a07baa5
Create Date: 2024-04-24 18:41:32.884470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d25b39d2113'
down_revision = '3c043a07baa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment_standard', schema=None) as batch_op:
        batch_op.drop_constraint('assessment_standard_component_id_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment_standard', schema=None) as batch_op:
        batch_op.create_unique_constraint('assessment_standard_component_id_key', ['component_id'])

    # ### end Alembic commands ###
