"""empty message

Revision ID: 5f7c3e2b05bb
Revises: c087829e37a2
Create Date: 2024-04-16 16:18:29.113283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f7c3e2b05bb'
down_revision = 'c087829e37a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('user_email', sa.String(length=319), nullable=False),
    sa.Column('user_first_name', sa.String(length=150), nullable=True),
    sa.Column('user_last_name', sa.String(length=150), nullable=True),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('user_password', sa.String(), nullable=True),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('staff_member', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.staff_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('assessment_scores', schema=None) as batch_op:
        batch_op.alter_column('assessment_score_id',
               existing_type=sa.INTEGER(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('standard_id',
               existing_type=sa.INTEGER(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('student_class_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.drop_column('column1')
        batch_op.drop_column('component_id')
        batch_op.drop_column('period')

    with op.batch_alter_table('classrooms', schema=None) as batch_op:
        batch_op.alter_column('school_name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=150),
               existing_nullable=True)
        batch_op.drop_column('grade_level')

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_name', sa.String(length=150)))
        batch_op.drop_column('name')

    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.Integer(), nullable=True))
        batch_op.alter_column('staff_name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=150),
               existing_nullable=True)
        batch_op.alter_column('staff_email',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.create_unique_constraint(None, ['staff_email'])
        batch_op.create_foreign_key(None, 'roles', ['role'], ['id'])
        batch_op.drop_column('staff_role')

    with op.batch_alter_table('student_classes', schema=None) as batch_op:
        batch_op.alter_column('student_class_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'roles', ['role'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('student_classes', schema=None) as batch_op:
        batch_op.alter_column('student_class_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('staff_role', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('staff_email',
               existing_type=sa.String(length=319),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('staff_name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.drop_column('role')

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
        batch_op.drop_column('role_name')

    with op.batch_alter_table('classrooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade_level', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.alter_column('school_name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    with op.batch_alter_table('assessment_scores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('period', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('component_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('column1', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.alter_column('student_class_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('standard_id',
               existing_type=sa.String(length=25),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('assessment_score_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    op.drop_table('users')
    # ### end Alembic commands ###
