"""empty message

Revision ID: 69dde5c1dc5a
Revises: 9d29778eb7d3
Create Date: 2024-05-22 12:13:33.439712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69dde5c1dc5a'
down_revision = '9d29778eb7d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment_component', schema=None) as batch_op:
        batch_op.alter_column('benchmark',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('assessment_score', schema=None) as batch_op:
        batch_op.drop_column('class_assessment_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment_score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class_assessment_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    with op.batch_alter_table('assessment_component', schema=None) as batch_op:
        batch_op.alter_column('benchmark',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
