"""empty message

Revision ID: 7d3687b39507
Revises: 3d25b39d2113
Create Date: 2024-04-26 09:05:07.327392

"""
from alembic import op
import sqlalchemy as sa
from models import Staff


# revision identifiers, used by Alembic.
revision = '7d3687b39507'
down_revision = '3d25b39d2113'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('user', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('profile', sa.String(length=100), nullable=False))
    #     batch_op.create_unique_constraint(None, ['profile'])
    #     batch_op.drop_constraint('staff_role_id_fkey', type_='foreignkey')
    #     batch_op.create_foreign_key(None, 'role', ['role_id'], ['id'], ondelete='cascade')
    

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_first_name')
        batch_op.drop_index('ix_user_last_name')
        batch_op.drop_index('ix_user_password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('ix_user_password_hash', ['password_hash'], unique=True)
        batch_op.create_index('ix_user_last_name', ['last_name'], unique=True)
        batch_op.create_index('ix_user_first_name', ['first_name'], unique=True)

    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('staff_role_id_fkey', 'role', ['role_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('profile')

    # ### end Alembic commands ###
