"""empty message

Revision ID: 917ec1b1a57b
Revises: 100a77119629
Create Date: 2024-04-24 12:39:24.778254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '917ec1b1a57b'
down_revision = '100a77119629'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('student_classroom_association', schema=None) as batch_op:
        batch_op.drop_column('id')
        batch_op.create_primary_key(None, 'student', ['student_id'], ['id'])
        batch_op.create_primary_key(None, 'classroom', ['classroom_id'], ['id'])

        
    

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_classroom_association', schema=None) as batch_op:
        batch_op.alter_column('student_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('student_id_seq'::regclass)"))

    with op.batch_alter_table('assessment_score', schema=None) as batch_op:
        batch_op.alter_column('student_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
