"""empty message

Revision ID: 9d29778eb7d3
Revises: 392beac1fb1e
Create Date: 2024-05-19 12:36:45.292845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d29778eb7d3'
down_revision = '392beac1fb1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment_score', schema=None) as batch_op:
        batch_op.drop_column('class_assessment_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment_score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class_assessment_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
