"""empty message

Revision ID: ae124f47127f
Revises: c55e56ce0ac5
Create Date: 2024-05-13 13:03:34.860376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae124f47127f'
down_revision = 'c55e56ce0ac5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment_score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score_tier', sa.String(), nullable=True))

    with op.batch_alter_table('assessment_standard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tier_minimum', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment_standard', schema=None) as batch_op:
        batch_op.drop_column('tier_minimum')

    with op.batch_alter_table('assessment_score', schema=None) as batch_op:
        batch_op.drop_column('score_tier')

    # ### end Alembic commands ###
