"""empty message

Revision ID: c55e56ce0ac5
Revises: b2062a6cc8df
Create Date: 2024-05-08 11:50:06.209430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c55e56ce0ac5'
down_revision = 'b2062a6cc8df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment_component', schema=None) as batch_op:
        batch_op.alter_column('subject',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('component_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('assessment_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('assessment_score', schema=None) as batch_op:
        batch_op.alter_column('period',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('component_id',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)

    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['profile'])
        batch_op.drop_constraint('staff_role_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'role', ['role_id'], ['id'], ondelete='cascade')

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['profile'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=100),
               nullable=True)
        batch_op.drop_index('ix_user_username')
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('ix_user_username', ['username'], unique=True)
        batch_op.alter_column('username',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=150),
               nullable=False)

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('staff_role_id_fkey', 'role', ['role_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('assessment_score', schema=None) as batch_op:
        batch_op.alter_column('component_id',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('period',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('assessment_component', schema=None) as batch_op:
        batch_op.alter_column('assessment_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('component_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('subject',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###
