"""empty message

Revision ID: c78ae741b086
Revises: 69dde5c1dc5a
Create Date: 2024-05-29 10:50:55.384122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c78ae741b086'
down_revision = '69dde5c1dc5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment_score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('standard_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'assessment_standard', ['standard_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment_score', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('standard_id')

    # ### end Alembic commands ###
